"""Compare hurdle March validation against hierarchical baseline (scripts 14–17)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

_SRC = Path(__file__).resolve().parent
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from _report_paths import (
    COMPARISON_DIR,
    HURDLE_VALIDATION_OVERALL,
    HURDLE_VALIDATION_PLANNING,
    ensure_report_dirs,
)

PROJECT_ROOT = _SRC.parent
WEEKLY_VERDICT = PROJECT_ROOT / "reports" / "weekly_tagged_systematic" / "weekly_tagged_verdict.json"
PROD_VERDICT = PROJECT_ROOT / "reports" / "production_granularity" / "production_granularity_verdict.json"
HOURLY_VERDICT = (
    PROJECT_ROOT / "reports" / "production_granularity" / "hourly_customer" / "hourly_customer_verdict.json"
)
OUT_MD = COMPARISON_DIR / "hurdle_vs_hierarchical.md"
OUT_CSV = COMPARISON_DIR / "hurdle_vs_hierarchical.csv"


def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _metric_df(overall: Path, planning: Path) -> dict[str, float]:
    out: dict[str, float] = {}
    if overall.exists():
        o = pd.read_csv(overall).set_index("metric")["value"].to_dict()
        out.update({str(k): float(v) for k, v in o.items()})
    if planning.exists():
        p = pd.read_csv(planning).set_index("metric")["value"].to_dict()
        for k, v in p.items():
            out[f"planning_{k}"] = float(v)
    return out


def main() -> int:
    ensure_report_dirs()
    hurdle = _metric_df(HURDLE_VALIDATION_OVERALL, HURDLE_VALIDATION_PLANNING)
    weekly = _load_json(WEEKLY_VERDICT)
    prod = _load_json(PROD_VERDICT)
    hourly = _load_json(HOURLY_VERDICT)

    rows = [
        {
            "layer": "hurdle_sliding_wcp_daily",
            "model": "04b_hurdle (hard + vol_scale)",
            "wmape": hurdle.get("monthly_wmape"),
            "bias_ratio": hurdle.get("monthly_bias_ratio"),
            "planning_window_loss": hurdle.get("planning_planning_window_loss")
            or hurdle.get("planning_window_loss"),
            "planning_composite": hurdle.get("planning_composite_loss")
            or hurdle.get("planning_composite_planning_loss"),
            "notes": "store×product×day sliding validation",
        },
        {
            "layer": "hierarchical_category_week",
            "model": weekly.get("selected_deployable_model", "tagged_systematic"),
            "wmape": weekly.get("selected_weekly_wmape") or prod.get("parent_category_week_wmape"),
            "bias_ratio": weekly.get("selected_weekly_bias_ratio"),
            "planning_window_loss": float("nan"),
            "planning_composite": float("nan"),
            "notes": "product_reference_group weekly parent",
        },
        {
            "layer": "hierarchical_category_day",
            "model": prod.get("selected_category_day_model"),
            "wmape": prod.get("category_day_wmape"),
            "bias_ratio": prod.get("parent_category_week_bias_ratio"),
            "planning_window_loss": float("nan"),
            "planning_composite": float("nan"),
            "notes": "reconciled category-day allocation",
        },
        {
            "layer": "hierarchical_product_day",
            "model": prod.get("selected_product_day_model"),
            "wmape": prod.get("product_day_wmape"),
            "bias_ratio": prod.get("parent_category_week_bias_ratio"),
            "planning_window_loss": float("nan"),
            "planning_composite": float("nan"),
            "notes": "reconciled product-day IPF",
        },
        {
            "layer": "hierarchical_customer_category_day",
            "model": hourly.get("selected_customer_category_day_model", "customer_category_janfeb_share"),
            "wmape": hourly.get("customer_category_day_wmape"),
            "bias_ratio": hourly.get("customer_category_day_bias_ratio"),
            "planning_window_loss": float("nan"),
            "planning_composite": float("nan"),
            "notes": "customer×category daily share",
        },
    ]
    df = pd.DataFrame(rows)
    df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

    q_target = hurdle.get("Q_target", float("nan"))
    md = f"""# Hurdle vs hierarchical baseline (March validation)

Generated by `src/06b_hurdle_vs_hierarchical.py`.

## Summary

| Layer | Model | WMAPE | Bias ratio | Planning window loss |
|-------|-------|------:|-----------:|-------------------:|
"""
    for _, r in df.iterrows():
        pw = r["planning_window_loss"]
        pw_s = f"{pw:.4f}" if pd.notna(pw) else "—"
        br = r["bias_ratio"]
        br_s = f"{br:+.4f}" if pd.notna(br) else "—"
        wm = r["wmape"]
        wm_s = f"{wm:.4f}" if pd.notna(wm) else "—"
        md += f"| {r['layer']} | {r['model']} | {wm_s} | {br_s} | {pw_s} |\n"

    md += f"""
## Interpretation

- **Hierarchical anchor** (`category-week`) achieves ~3.6% WMAPE by forecasting broad product-reference-group weekly totals with calendar/price context, then allocating down.
- **Hurdle** operates at `(warehouse, store, product)` daily grain with a classifier + size model; it struggles on **intermittent sparse orders** and **day timing** unless threshold/calibration align with planning metrics.
- **Planning window loss** (±2d product match) is only reported for hurdle in this table; hierarchical scripts optimize WMAPE at coarser grains.
- **Q_target** (hurdle run): `{q_target:,.1f}` — mean of Jan and Mar network daily totals.

## Why hurdle underperforms at comparable grains

1. **Grain mismatch**: hierarchical model wins at category-week; hurdle is evaluated at store×product×day where WMAPE is inherently higher (~19% product-day for hierarchical vs hurdle monthly WMAPE on WCP series).
2. **Intermittency**: most panel rows are zero; hard hurdle suppresses orders when P(order) is low; soft hurdle fixes volume but creates phantom order lines (bad planning loss).
3. **Sliding window**: 7-day blocks misalign with weekly category forecasts used by the hierarchical system.
4. **No top-down reconciliation**: hurdle does not constrain product totals to category-week anchors.

## Detail files

| File | Contents |
|------|----------|
| `comparison/hurdle_vs_hierarchical.csv` | Metric table |
| `hurdle/hurdle_validation_overall.csv` | Hurdle daily/monthly metrics |
| `hurdle/hurdle_validation_planning_loss.csv` | Hurdle planning loss breakdown |
| `weekly_tagged_systematic/weekly_tagged_verdict.json` | Parent weekly model selection |
| `production_granularity/production_granularity_verdict.json` | Day/product layer metrics |
"""
    OUT_MD.write_text(md, encoding="utf-8")
    print(f"Wrote {OUT_MD.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
